import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { MainProvider } from "@/context/MainContext";
import NavTop from "@/components/Navbar/NavbarTop";
import NavMiddle from "@/components/Navbar/NavMiddle";
import NavBottom from "@/components/Navbar/NavBottom";
import Footer from "@/components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <MainProvider>
            <NavTop />
            <NavMiddle />
            <NavBottom />
            {children}
            <Footer />
          </MainProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
